version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: hackathon_postgres
    environment:
      POSTGRES_DB: HackathonService
      POSTGRES_USER: hackathon_user
      POSTGRES_PASSWORD: khoa261204
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hackathon_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hackathon_user -d HackathonService"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  hackathon_network:
    driver: bridge
